export const ACTION_TYPES = {
  TOGGLE_DARK_MODE: "TOGGLE_DARK_MODE",
  SET_RESULT: "SET_RESULT",
  SET_FIRST_OPERAND: "SET_FIRST_OPERAND",
  SET_OPERATION: "SET_OPERATION",
  CLEAR_DATA: "CLEAR_DATA",
};
